'use client'
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "./hooks/state/theme-provider";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { SelectedValuesProvider } from "./hooks/state/selected-values";
import { Toaster } from "sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const queryClient = new QueryClient();

  return (
    <html lang="en">
      <meta httpEquiv="Content-Security-Policy" content="upgrade-insecure-requests"></meta>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <QueryClientProvider client={queryClient}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <SelectedValuesProvider>
              {children}
              <Toaster />
            </SelectedValuesProvider>
          </ThemeProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
